#!/bin/bash

case "$1" in

  start)
    printf "Starting iptables: "
    iptables -t nat -A OUTPUT -p tcp -m owner --uid-owner proxied -j REDIRECT --to-ports 3128
    echo "OK"
    ;;

  stop)
    printf "Stopping iptables: "
    iptables -t nat -D OUTPUT -p tcp -m owner --uid-owner proxied -j REDIRECT --to-ports 3128
    echo "OK"
    ;;

  *)
    echo "Usage: $0 {start|stop}"
    exit 1

esac
